// SPDX-License-Identifier: Apache-2.0
// Generated by erc20gen — https://github.com/Zubimendi/erc20gen
// ⚠️  SECURITY: Audit this contract before deploying to mainnet.
// Run: slither contracts/gyokeres.sol && echidna-test . --contract gyokeres
pragma solidity ^0.8.24;
import "@openzeppelin/contracts/token/ERC20/ERC20.sol";
import "@openzeppelin/contracts/token/ERC20/extensions/ERC20Capped.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

/**
 * @title gyokeres
 * @dev ERC-20 Token — G14
 *
 * Features:
 *   ✓ Capped Supply   — maximum 1000000 tokens
 *
 * Access Control: ownable
 * Generated: erc20gen v1.0.0
 */
contract gyokeres is ERC20, ERC20Capped, Ownable {

    /**
     * @dev Initializes the token with name, symbol, and initial supply.
     *      Initial supply is minted to the deployer address.
     * @param initialOwner The address that receives the initial supply and admin role.
     */
    constructor(address initialOwner)
        ERC20("gyokeres", "G14")
        ERC20Capped(1000000 * 10 ** decimals())
        Ownable(initialOwner)
    {
        // Mint initial supply to deployer.
        // NOTE: decimals() is called after ERC20 is initialized, safe here.
        _mint(initialOwner, 1000000 * 10 ** decimals());
    }

    /**
     * @dev Overrides the default 18 decimals.
     */
    function decimals() public pure override returns (uint8) {
        return 6;
    }

    // ─── Internal overrides ──────────────────────────────────────────────────

    function _update(address from, address to, uint256 value)
        internal
        override(ERC20, ERC20Capped)
    {
        super._update(from, to, value);
    }
}
