// Hardhat deployment script for gyokeres (G14)
// Generated by erc20gen — https://github.com/Zubimendi/erc20gen
//
// Usage:
//   npx hardhat run scripts/deploy_gyokeres.js --network <network>
//
// Security checklist before deploying:
//   1. Set DEPLOYER_PRIVATE_KEY in .env (never commit this file!)
//   2. Verify contract source on Etherscan after deployment
//   3. Transfer ownership if needed BEFORE publicizing the contract

const { ethers } = require("hardhat");

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log("Deploying gyokeres with account:", deployer.address);
  console.log("Account balance:", (await deployer.provider.getBalance(deployer.address)).toString());

  const gyokeres = await ethers.getContractFactory("gyokeres");
  // Pass initialOwner — receives initial supply and admin rights
  const token = await gyokeres.deploy(deployer.address);

  await token.waitForDeployment();
  const address = await token.getAddress();

  console.log("\n✅ gyokeres deployed to:", address);
  console.log("   Symbol:         G14");
  console.log("   Decimals:       6");
  console.log("   Initial Supply: 1000000 tokens");
  console.log("   Max Supply:     1000000 tokens");

  // Verify on Etherscan (requires ETHERSCAN_API_KEY in hardhat.config.js)
  if (process.env.ETHERSCAN_API_KEY) {
    console.log("\nWaiting for block confirmations before verification...");
    await token.deploymentTransaction().wait(6);
    await hre.run("verify:verify", {
      address,
      constructorArguments: [deployer.address],
    });
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
